import { Refine } from "@refinedev/core";
import { RefineKbar, RefineKbarProvider } from "@refinedev/kbar";
import routerProvider from "@refinedev/nextjs-router";
import { Metadata } from "next";
import React, { Suspense, useState } from "react";

import { authProvider } from "@providers/auth-provider";
import { dataProvider } from "@providers/data-provider";
import "@styles/global.css";

import {
  RefineThemes,
  ThemedLayoutV2,
  refineTheme,
} from "@refinedev/chakra-ui";
import { ChakraProvider } from "@chakra-ui/react";
import { customTheme } from "./customThemes";

export const metadata: Metadata = {
  title: "Refine",
  description: "Generated by create refine app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Suspense>
          {/* <GitHubBanner /> */}
          <RefineKbarProvider>
            {/* <DevtoolsProvider> */}
            <ChakraProvider theme={customTheme}>
              <Refine
                routerProvider={routerProvider}
                dataProvider={dataProvider}
                authProvider={authProvider}
                resources={[
                  {
                    name: "blog_posts",
                    list: "/blog-posts",
                    create: "/blog-posts/create",
                    edit: "/blog-posts/edit/:id",
                    show: "/blog-posts/show/:id",
                    meta: {
                      canDelete: true,
                    },
                  },
                  {
                    name: "categories",
                    list: "/categories",
                    create: "/categories/create",
                    edit: "/categories/edit/:id",
                    show: "/categories/show/:id",
                    meta: {
                      canDelete: true,
                    },
                  },
                ]}
                options={{
                  syncWithLocation: true,
                  warnWhenUnsavedChanges: true,
                  useNewQueryKeys: true,
                  projectId: "361yPh-CVndCE-W01UqO",
                }}
              >
                {/* <ThemedLayoutV2> */}

                {children}
                {/* </ThemedLayoutV2> */}
                <RefineKbar />
              </Refine>
            </ChakraProvider>
            {/* </DevtoolsProvider> */}
          </RefineKbarProvider>
        </Suspense>
      </body>
    </html>
  );
}
